[package]
name = "base64_nif"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "base64_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
base64 = "0.20.0-alpha.0"
