[package]
name = "base64_nif"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "base64_nif"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0-rc.0"
base64 = "0.12.0"
